//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IngredientInventory
    {
        public System.Guid IngredientID { get; set; }
        public string ItemNumber { get; set; }
        public string IngredientDescription { get; set; }
        public string IngredientDescriptionAddl { get; set; }
        public Nullable<int> IngredientCategory { get; set; }
        public int StockCount { get; set; }
        public int UOM { get; set; }
        public Nullable<decimal> CostPerUnit { get; set; }
        public Nullable<int> Location { get; set; }
        public Nullable<int> ReorderLevel { get; set; }
        public Nullable<int> ReorderQty { get; set; }
        public Nullable<System.DateTime> LastReorderDate { get; set; }
        public int SupplierID { get; set; }
        public string Comment { get; set; }
        public bool Active { get; set; }
        public bool Deleted { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string LastUpdateUser { get; set; }
    }
}
