//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BakeryWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class pmanuelEntities : DbContext
    {
        public pmanuelEntities()
            : base("name=pmanuelEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<IngredientCategory> IngredientCategories { get; set; }
        public virtual DbSet<IngredientInventory> IngredientInventories { get; set; }
        public virtual DbSet<IngredientSupplier> IngredientSuppliers { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<UOM> UOMs { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
    
        public virtual int bdbResetData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bdbResetData");
        }
    
        public virtual int bdbResetSchema()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("bdbResetSchema");
        }
    }
}
